rest_oai_pmh:
  entity_type: node
_core:
  default_config_hash: aJbCDXJg1plAZOBvfb4BMjYJ7hiJbTHKxeCAvDrBiSQ
repository_path: /oai/request
view_displays:
  'cw_phm:entity_reference_1': 'cw_phm:entity_reference_1'
support_sets: 1
metadata_map_plugins:
  -
    label: mods
    value: ''
  -
    label: oai_dc
    value: dublin_core_metatag
  -
    label: oai_raw
    value: default_metadata_map
repository_name: ELMCIP
repository_email: a@a.b
expiration: '3600'
cache_technique: conservative_cache
mods_view:
  view_machine_name: ''
  view_display_name: ''
